import { useState, useEffect, useCallback, useRef } from "react";

export interface TelemetryPoint {
  id: string;
  symbol: string;
  name: string;
  category: "biosphere" | "climatology" | "oceans_ice" | "bioeconomy";
  value: number;
  unit: string;
  baseline: string;
  change24h: number;
  history: number[];
  station: string;
  sensorModel: string;
  precision: number;
  macroContext: string;
  driftRange: [number, number]; // [min, max] realistic bounding range
  volatility: number; // typical step variance
}

export const INITIAL_PLANETARY_TELEMETRY: TelemetryPoint[] = [
  {
    id: "CO2_ATMOS",
    symbol: "CO₂_MLO",
    name: "Atmospheric Carbon Dioxide",
    category: "climatology",
    value: 426.84,
    unit: "ppm",
    baseline: "280.0 ppm (Pre-industrial)",
    change24h: 0.12,
    history: [426.71, 426.74, 426.78, 426.8, 426.82, 426.81, 426.84],
    station: "Mauna Loa Observatory, HI (NOAA / GML)",
    sensorModel: "Picarro G2401 Cavity Ring-Down Spectrometer",
    precision: 2,
    macroContext: "Continuous atmospheric carbon density at high elevation baseline. Captures seasonal photosynthetic drawdown and multi-decadal accumulation.",
    driftRange: [426.2, 427.4],
    volatility: 0.03
  },
  {
    id: "TEMP_ANOMALY",
    symbol: "ERA5_TEMP",
    name: "Global Mean Surface Temp Anomaly",
    category: "climatology",
    value: 1.284,
    unit: "°C",
    baseline: "1850-1900 Climatological Baseline",
    change24h: 0.08,
    history: [1.272, 1.275, 1.279, 1.281, 1.28, 1.283, 1.284],
    station: "Copernicus Climate Change Service / ECMWF",
    sensorModel: "ERA5 Global Reanalysis & Satellite Microwave Radiometers",
    precision: 3,
    macroContext: "Deviation from pre-industrial global mean surface air temperature. Reflects marine heatwaves and continental summer anomalies.",
    driftRange: [1.26, 1.32],
    volatility: 0.003
  },
  {
    id: "ARCTIC_ICE",
    symbol: "ARC_EXTENT",
    name: "Arctic Sea Ice Minimum Extent",
    category: "oceans_ice",
    value: 4.382,
    unit: "M km²",
    baseline: "6.85 M km² (1981-2010 Median)",
    change24h: -0.34,
    history: [4.44, 4.42, 4.41, 4.395, 4.39, 4.385, 4.382],
    station: "National Snow and Ice Data Center (NSIDC)",
    sensorModel: "DMSP SSMIS Microwave Imager & CryoSat-2 Radar Altimeter",
    precision: 3,
    macroContext: "Daily polar sea ice coverage during the late summer melt window. Critical regulator of the planetary albedo feedback mechanism.",
    driftRange: [4.32, 4.48],
    volatility: 0.004
  },
  {
    id: "OCEAN_PH",
    symbol: "PAC_PH",
    name: "Pacific Surface Acidification",
    category: "oceans_ice",
    value: 8.041,
    unit: "pH",
    baseline: "8.25 pH (Pre-industrial average)",
    change24h: -0.02,
    history: [8.048, 8.046, 8.045, 8.044, 8.042, 8.043, 8.041],
    station: "Station ALOHA, North Pacific Subtropical Gyre",
    sensorModel: "Sea-Bird Deep SUNA UV Optical Nitrate / pH Profiler",
    precision: 3,
    macroContext: "Alkalinity index in upper epipelagic waters. Measures calcification stress on planktonic and pteropod shells.",
    driftRange: [8.035, 8.05],
    volatility: 0.001
  },
  {
    id: "CANOPY_TRANSPIRATION",
    symbol: "JURUÁ_EVAP",
    name: "Amazon Canopy Transpiration Rate",
    category: "biosphere",
    value: 4.218,
    unit: "L/m²/d",
    baseline: "4.50 L/m²/d (Nominal Moist Season)",
    change24h: 1.45,
    history: [4.12, 4.14, 4.16, 4.19, 4.2, 4.21, 4.218],
    station: "Juruá River Basin Biological Reserve, Tower 4",
    sensorModel: "Campbell Scientific IRGASON Integrated Eddy Covariance",
    precision: 3,
    macroContext: "Atmospheric moisture pump generated by old-growth primary rainforest canopies sustaining continental 'flying rivers.'",
    driftRange: [4.05, 4.4],
    volatility: 0.015
  },
  {
    id: "SOIL_MOISTURE",
    symbol: "SOIL_VWC",
    name: "Sub-Canopy Soil Volumetric Moisture",
    category: "biosphere",
    value: 33.24,
    unit: "% VWC",
    baseline: "35.0% VWC (Field Capacity)",
    change24h: 0.62,
    history: [32.8, 32.9, 33.0, 33.1, 33.15, 33.2, 33.24],
    station: "Mamirauá Institute Ecological Grid Station B",
    sensorModel: "Decagon 5TM Soil Moisture & Temperature Time-Domain Array",
    precision: 2,
    macroContext: "Root-zone volumetric water content at 50cm depth under dense tropical foliage.",
    driftRange: [31.5, 35.5],
    volatility: 0.08
  },
  {
    id: "BIODIVERSITY_INDEX",
    symbol: "BIO_DIV_S8",
    name: "Planetary Bioacoustic Density Index",
    category: "biosphere",
    value: 92.48,
    unit: "pts",
    baseline: "100.0 pts (Intact Reference Biome)",
    change24h: 1.84,
    history: [90.2, 90.8, 91.3, 91.8, 92.1, 92.3, 92.48],
    station: "London AI Center / Mamirauá Bioacoustic Grid",
    sensorModel: "Aura-8 Transformer Neural Audio Classifier (1,248 Nodes)",
    precision: 2,
    macroContext: "Composite metric quantifying acoustic niche richness and biophonic frequency partitioning across multi-canopy layers.",
    driftRange: [89.0, 95.0],
    volatility: 0.12
  },
  {
    id: "CARBON_CREDIT_SPOT",
    symbol: "AMZN_OFFSET",
    name: "Verified Old-Growth Carbon Offset",
    category: "bioeconomy",
    value: 142.85,
    unit: "$/t CO₂e",
    baseline: "$100.00 / t (Base Tier)",
    change24h: 1.68,
    history: [139.5, 140.2, 141.0, 141.6, 142.1, 142.4, 142.85],
    station: "Global Forest Ledger / Zurich Carbon Exchange",
    sensorModel: "LiDAR High-Resolution Biomass Verification Protocol",
    precision: 2,
    macroContext: "Spot clearing price for sovereign-backed, high-integrity verified ecological credits with biodiversity co-benefits.",
    driftRange: [136.0, 149.0],
    volatility: 0.25
  },
  {
    id: "RENEWABLE_GRID",
    symbol: "GRID_ECO",
    name: "Global Renewable Generation Share",
    category: "bioeconomy",
    value: 36.42,
    unit: "%",
    baseline: "30.0% (2024 Benchmark)",
    change24h: 2.15,
    history: [35.2, 35.5, 35.8, 36.0, 36.15, 36.3, 36.42],
    station: "International Energy Agency (IEA) Live Grid Telemetry",
    sensorModel: "Real-time Continental Inverter & Synchronous Dispatch Feed",
    precision: 2,
    macroContext: "Instantaneous planetary electricity generation from solar, wind, geothermal, and run-of-river hydro.",
    driftRange: [34.0, 39.0],
    volatility: 0.08
  },
  {
    id: "ACTIVE_ACOUSTIC_NODES",
    symbol: "NODE_LIVE",
    name: "Aura Bioacoustic Grid Nodes Active",
    category: "biosphere",
    value: 1248,
    unit: "nodes",
    baseline: "1,200 deployed baseline",
    change24h: 0.0,
    history: [1240, 1244, 1246, 1248, 1248, 1248, 1248],
    station: "Mamirauá Juruá-Solimões Grid",
    sensorModel: "LoRaWAN Ultra-Low-Power Acoustic Array Nodes",
    precision: 0,
    macroContext: "Number of active, telemetry-streaming acoustic listener canisters mounted in primary flooded and terra firme biomes.",
    driftRange: [1240, 1250],
    volatility: 1
  }
];

export function usePlanetaryTelemetry(autoRefreshIntervalMs: number = 3000) {
  const [telemetry, setTelemetry] = useState<TelemetryPoint[]>(INITIAL_PLANETARY_TELEMETRY);
  const [lastSyncTime, setLastSyncTime] = useState<Date>(new Date());
  const [syncCount, setSyncCount] = useState<number>(0);
  const [isLiveStreaming, setIsLiveStreaming] = useState<boolean>(true);
  const [streamLatencyMs, setStreamLatencyMs] = useState<number>(24);
  const [flashingIds, setFlashingIds] = useState<Record<string, "up" | "down" | null>>({});

  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const tickTelemetry = useCallback(() => {
    setTelemetry((prev) => {
      const nextFlash: Record<string, "up" | "down" | null> = {};
      const updated = prev.map((item) => {
        // 55% chance each metric experiences natural sensory fluctuation
        if (Math.random() > 0.55) return item;

        const isUp = Math.random() > 0.47;
        const step = (Math.random() * item.volatility * (isUp ? 1 : -1));
        let nextVal = item.value + step;

        // Keep strictly within realistic scientific bounds
        if (nextVal < item.driftRange[0]) nextVal = item.driftRange[0] + Math.random() * item.volatility;
        if (nextVal > item.driftRange[1]) nextVal = item.driftRange[1] - Math.random() * item.volatility;

        const formattedVal = Number(nextVal.toFixed(item.precision));
        const delta = formattedVal - item.value;
        const nextChange = Number((item.change24h + (delta / (item.value || 1)) * 100).toFixed(2));

        const nextHistory = [...item.history.slice(1), formattedVal];
        nextFlash[item.id] = isUp ? "up" : "down";

        return {
          ...item,
          value: formattedVal,
          change24h: nextChange,
          history: nextHistory,
        };
      });

      setFlashingIds(nextFlash);
      setTimeout(() => setFlashingIds({}), 700);
      return updated;
    });

    setLastSyncTime(new Date());
    setSyncCount((c) => c + 1);
    setStreamLatencyMs(Math.floor(18 + Math.random() * 14));
  }, []);

  const forceSync = useCallback(() => {
    tickTelemetry();
  }, [tickTelemetry]);

  useEffect(() => {
    if (!isLiveStreaming) return;
    timerRef.current = setInterval(() => {
      tickTelemetry();
    }, autoRefreshIntervalMs);

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [isLiveStreaming, autoRefreshIntervalMs, tickTelemetry]);

  return {
    telemetry,
    lastSyncTime,
    syncCount,
    isLiveStreaming,
    setIsLiveStreaming,
    streamLatencyMs,
    flashingIds,
    forceSync,
  };
}
